apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro690
  labels:
    app: argo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pro690
  template:
    metadata:
      labels:
        app: pro690
    spec:
      containers:
        - name: pro690
          image: darshpadaria/pro690:v1.0
          ports:
            - containerPort: 8080